name: 'benchmark'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v1

      - uses: bahmutov/npm-install@v1

      - uses: RobbinBaauw/benchmark-action@v1.0.0-alpha.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: packages/benchmark/out.json
          benchmark_script: benchmark
